name: Build package

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: 'Package Version'
        required: false
        type: string

jobs:
  package:
    runs-on: ubuntu-latest

    name: Build package
    steps:
    - uses: actions/checkout@v3

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        path: README.md
