name: Build package

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: 'Package Version'
        required: false
        type: string

jobs:
  package:
    runs-on: ubuntu-latest

    name: Build package
    steps:
    - uses: actions/checkout@v3

    - name: Set version
      env:
        PACKAGE_VERSION: ${{ github.event.inputs.packageVersion }}
      run: 'sed -Ei "s/test.*/test-${PACKAGE_VERSION}/g" README.md'
      if: github.event.inputs.packageVersion
      
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: woocommerce-paypal-payments
        path: README.md
